export const FETCH_AUTH_ID = "FETCH_AUTH_ID";
export const REMOVE_AUTH_ID = "REMOVE_AUTH_ID";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const FETCH_DOCTOR_LIST = "FETCH_DOCTOR_LIST";
export const REMOVE_DOCTOR_LIST = "REMOVE_DOCTOR_LIST";

export const FETCH_APPOINTMENT_LIST = "FETCH_APPOINTMENT_LIST";
export const REMOVE_APPOINTMENT_LIST = "REMOVE_APPOINTMENT_LIST";

export const FETCH_FCM_TOKEN = "FETCH_FCM_TOKEN";
export const REMOVE_FCM_TOKEN = "REMOVE_FCM_TOKEN";