import { Platform, StyleSheet } from 'react-native'
import { COLOR } from '../../constants/Colors'
import { ResponsiveSizeWp } from '../../constants/Responsive'
import { FontFamily } from '../../constants/Fonts'

export const styles = StyleSheet.create({
    Container: {
        flex: 1,
        backgroundColor: COLOR.WHITE,
    },
    ContentContainer: {
        paddingHorizontal: ResponsiveSizeWp(15),
        paddingBottom: ResponsiveSizeWp(140),
    },
    HeaderContainer: {
        backgroundColor: COLOR.PRIMARYCOLOR,
        width: '100%',
        paddingTop: ResponsiveSizeWp(50),
    },
    HeaderContentContainer: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: ResponsiveSizeWp(15),
        paddingVertical: ResponsiveSizeWp(10),
    },
    HeaderText: {
        fontFamily: FontFamily.SemiBold,
        fontSize: ResponsiveSizeWp(20),
        color: COLOR.WHITE,
        marginLeft: ResponsiveSizeWp(10),
        flex: 1,
    },
    DoctorContainer: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: ResponsiveSizeWp(15),
        paddingHorizontal: ResponsiveSizeWp(20),
        backgroundColor: COLOR.BLACK_20,
        marginTop: ResponsiveSizeWp(10),
        gap: ResponsiveSizeWp(15),
    },
    DoctorDetailsContainer: {
        flex: 1,
        alignItems: 'flex-end',
    },
    DoctorNameText: {
        fontFamily: FontFamily.SemiBold,
        color: COLOR.WHITE,
        fontSize: ResponsiveSizeWp(18),
        textAlign: 'right',
    },
    DoctorDesignationText: {
        fontFamily: FontFamily.Regular,
        color: COLOR.WHITE,
        fontSize: ResponsiveSizeWp(12),
        textAlign: 'right',
    },
    StepContainer: {
        flexDirection: 'row',
        paddingVertical: ResponsiveSizeWp(30),
        alignItems: 'center',
    },
    Step: {
        flex: 1,
        alignItems: 'center',
    },
    StepLine: {
        width: ResponsiveSizeWp(30),
        height: ResponsiveSizeWp(1),
        backgroundColor: COLOR.LIGHTGRAYBORDER,
        marginBottom: ResponsiveSizeWp(25),
        borderRadius: ResponsiveSizeWp(10),
    },
    StepCircle: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLOR.LIGHTGRAYBORDER,
        alignSelf: 'center',
        height: ResponsiveSizeWp(60),
        aspectRatio: 1 / 1,
        borderRadius: ResponsiveSizeWp(40),
    },
    StepText: {
        fontFamily: FontFamily.SemiBold,
        fontSize: ResponsiveSizeWp(30),
        color: COLOR.WHITE,
        top: Platform.OS == 'android' ? ResponsiveSizeWp(4) : 0,
    },
    StepDescText: {
        fontFamily: FontFamily.Regular,
        fontSize: ResponsiveSizeWp(12),
        color: COLOR.BLACK_50,
        marginTop: ResponsiveSizeWp(7),
    },
    TitleText: {
        fontSize: ResponsiveSizeWp(20),
        color: COLOR.BLACK,
        fontFamily: FontFamily.Medium,
        paddingHorizontal: ResponsiveSizeWp(15),
    },
    ModeSelection: {
        width: '100%',
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: ResponsiveSizeWp(10),
        paddingHorizontal: ResponsiveSizeWp(15),
    },
    ModeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: ResponsiveSizeWp(15),
        paddingVertical: ResponsiveSizeWp(8),
        backgroundColor: COLOR.LIGHTGRAY,
        marginRight: ResponsiveSizeWp(15),
        borderRadius: ResponsiveSizeWp(12),
        borderWidth: ResponsiveSizeWp(1),
        borderColor: COLOR.PRIMARYCOLOR,
    },
    ModeIcon: {
        tintColor: COLOR.MOSSGREEN,
        width: ResponsiveSizeWp(30),
        aspectRatio: 1 / 1,
        resizeMode: 'contain',
    },
    ModeText: {
        marginLeft: ResponsiveSizeWp(10),
        color: COLOR.BLACK,
        fontFamily: FontFamily.SemiBold,
        fontSize: ResponsiveSizeWp(15),
    },
    DescText: {
        fontSize: ResponsiveSizeWp(15),
        color: COLOR.GRAY,
        fontFamily: FontFamily.Medium,
        paddingHorizontal: ResponsiveSizeWp(15),
        marginTop: ResponsiveSizeWp(20),
    },
    PaymentContainer: {
        flex: 1,
        paddingVertical: ResponsiveSizeWp(8),
        flexDirection: 'row',
        backgroundColor: COLOR.WHITE,
        borderWidth: 1,
        marginHorizontal: ResponsiveSizeWp(10),
        marginTop: ResponsiveSizeWp(5),
        borderRadius: ResponsiveSizeWp(6),
        paddingHorizontal: ResponsiveSizeWp(8),
        borderColor: COLOR.LIGHTGRAYBORDER,
        alignItems: 'center',
    },
    CardIcon: {
        width: ResponsiveSizeWp(30),
        resizeMode: 'contain',
        aspectRatio: 2 / 1,
    },
    container: {
        flex: 1,
        paddingHorizontal: ResponsiveSizeWp(10),
    },
    radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: ResponsiveSizeWp(20),
        marginTop: ResponsiveSizeWp(20),
    },
    label: {
        fontSize: ResponsiveSizeWp(16),
        fontFamily: FontFamily.SemiBold,
        marginLeft: ResponsiveSizeWp(10),
        color: COLOR.BLACK,
    },
    inputLabel: {
        fontSize: ResponsiveSizeWp(14),
        fontFamily: FontFamily.SemiBold,
        marginBottom: ResponsiveSizeWp(5),
        color: COLOR.BLACK,
    },
    cardInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLOR.WHITE,
        borderRadius: ResponsiveSizeWp(5),
        borderWidth: ResponsiveSizeWp(1),
        borderColor: COLOR.LIGHTGRAYBORDER,
        paddingHorizontal: ResponsiveSizeWp(10),
        marginBottom: ResponsiveSizeWp(20),
    },
    cardIcon: {
        width: ResponsiveSizeWp(30),
        height: ResponsiveSizeWp(30),
        marginRight: ResponsiveSizeWp(10),
    },
    cardInput: {
        flex: 1,
        fontSize: ResponsiveSizeWp(16),
        fontFamily: FontFamily.Regular,
        padding: ResponsiveSizeWp(10),
        color: COLOR.BLACK,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    inputGroup: {
        flex: 1,
        marginRight: ResponsiveSizeWp(10),
        color: COLOR.BLACK,
    },
    expiryContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    expiryInput: {
        flex: 1,
        borderWidth: ResponsiveSizeWp(1),
        borderColor: COLOR.LIGHTGRAYBORDER,
        borderRadius: ResponsiveSizeWp(5),
        fontFamily: FontFamily.Regular,
        padding: ResponsiveSizeWp(10),
        marginRight: ResponsiveSizeWp(5),
        textAlign: 'center',
        backgroundColor: COLOR.WHITE,
        color: COLOR.BLACK,
    },
    cvvInput: {
        flex: 1,
        borderWidth: ResponsiveSizeWp(1),
        borderColor: COLOR.LIGHTGRAYBORDER,
        borderRadius: ResponsiveSizeWp(5),
        fontFamily: FontFamily.Regular,
        padding: ResponsiveSizeWp(10),
        textAlign: 'center',
        color: COLOR.BLACK,
        backgroundColor: COLOR.WHITE,
    },
    upiLogo: {
        width: ResponsiveSizeWp(80),
        aspectRatio: 3 / 1,
        resizeMode: 'contain',
        marginRight: ResponsiveSizeWp(5),
        marginLeft: ResponsiveSizeWp(10),
    },
    LoaderContainer: {
        height: ResponsiveSizeWp(300),
        justifyContent: 'center',
    },
})