export const FontFamily = {
    Regular: 'Poppins-Regular',
    Italic: 'Poppins-Italic',
    Bold: 'Poppins-Bold',
    BoldItalic: 'Poppins-BoldItalic',
    ExtraBold: 'Poppins-ExtraBold',
    ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    ExtraLight: 'Poppins-ExtraLight',
    ExtraLightItalic: 'Poppins-ExtraLightItalic',
    Light: 'Poppins-Light',
    LightItalic: 'Poppins-LightItalic',
    Medium: 'Poppins-Medium',
    MediumItalic: 'Poppins-MediumItalic',
    SemiBold: 'Poppins-SemiBold',
    SemiBoldItalic: 'Poppins-SemiBoldItalic',
    Thin: 'Poppins-Thin',
    ThinItalic: 'Poppins-ThinItalic',
    Black: 'Poppins-Black',
    BlackItalic: 'Poppins-BlackItalic',
};