export const keyboardType = {
    ascii_capable: 'ascii-capable',
    decimal_pad: 'decimal-pad',
    default: 'default',
    email_address: 'email-address',
    name_phone_pad: 'name-phone-pad',
    number_pad: 'number-pad',
    numbers_and_punctuation: 'numbers-and-punctuation',
    numeric: 'numeric',
    phone_pad: 'phone-pad',
    twitter: 'twitter',
    url: 'url',
    visible_password: 'visible-password',
    web_search: 'web-search',
}